accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts_api"

urlpatterns = [
    path('user/', views.user_view.as_view(), name='get_user'),                       #Check user api
    path('register', views.register_view.as_view(), name='register_user'),              #Register User
    path('welcome/email/',  views.welcome_email_view, name='welcome_email'),               #send verification email link

    path('login', views.login_view.as_view(), name='login_user'),                       #API login validator

    path('set_password', views.setting_password, name='set_password'),
    path('auth/', include('dj_rest_auth.urls')),
    #path('auth/', include('dj_rest_auth.urls', namespace='djrest_api')),                #dj rest auth login, change password etc
    path('google-login', views.googleLogin_view, name='login_with_google'),              #Login with Google
    path('verify/email/',  views.verify_email_view, name='verify_email'),               #send verification email link
    path('confirm/email/<uidb64>/<token>/',  views.activate, name='activate'),       #Verify the email
    path('check_user/<user>', views.check_user.as_view(), name='check_user'),

    path('wait', views.WaitLists.as_view(), name='wait'),
    path('feedback', views.Feedbacks.as_view(), name='feedback'),





    # URLs that do not require user to be logged in djrest auth.
    # ---------------------------------------------------------------------------
    # login/                  Login Url
    # password/reset/         Reset password
    # password-reset/confirm/<uidb64>/<token>/        Reset password link
    
    # URLs that require a user to be logged in djrest auth.
    # -----------------------------------------------------------------------
    # logout/                 Logout url
    # user/                   Check the user who is logged in
    # password/change/        Change the logged in user password
    # token/verify/           verify token
    # token/refresh/          Refresh the jwt token
                

]

familyalbum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('settingss/', include('appSettings.urls')),
    path('accounts/', include('accounts.urls')),
    path('allauth/', include('allauth.urls')),
    path('albums/', include('albums.urls')),
    path('email/', include('emailapp.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feeds/urls.py
from django.urls import path, include
from . import views

app_name = "feeds_api"

urlpatterns = [
    path('post', views.posting.as_view(), name='posting'),
    path('comment', views.commenting.as_view(), name='commenting'),

    path('view_all/<albumid>', views.view_feed.as_view(), name='view_feed'),
    path('view_post/<postid>', views.view_post.as_view(), name='view_post'),
    path('view_comment/<postid>', views.view_comments.as_view(), name='view_comments'),

    path('delete_post', views.delete_post.as_view(), name='delete_post'),
    path('delete_comment', views.delete_comment.as_view(), name='delete_comment'),

]

accounts/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render, get_object_or_404,redirect

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated


from . import serializers
from .models import Account,SocialLogin,WaitList,Feedback

#For authentication
from django.contrib.auth import authenticate,logout

#For gmail login
from django.contrib.auth.decorators import login_required

#For email verification
from rest_framework.decorators import api_view, permission_classes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from django.core.mail import EmailMessage, message
from django.conf import settings
from .tasks import celery_verify_email

class check_user(APIView):
    def get(self,request,user):
        data ={}
        try:
            if Account.objects.filter(Q(username=user)|Q(email=user)).exists() == True:
                account = Account.objects.get(Q(username=user)|Q(email=user))
                result = True
                data["username"]     = account.username
                data["fullname"]     = account.fullname
                data['profile_image']  = str(account.profile_image.url)
            else:
                result = False
            data["result"]     = result
        except:
            data["Error"]     = "Sorry something when wrong"
        return Response(data=data)

# Create your views here.
class user_view(APIView):
    permission_classes = [IsAuthenticated]


    def get(self, request):
        data = {}
        # check if user exist 
        user =  get_object_or_404(Account, email=request.user)
        serializer = serializers.AccountSerializer(user)

        data = serializer.data
        data['email_verified'] = user.email_verified

        data['profile_image'] = data['profile_image']
        if user.plan != None:
            data['plan'] = user.plan.space_size
            data['plan_desc'] = user.plan.desc
            data['amount'] = user.plan.amount
        else:
            data['plan'] = None
            data['plan_desc'] = None
            data['amount'] = None
        return Response(data, status=status.HTTP_200_OK)


     #for Updating user 
    def put(self, request):
        data = {}
        user =  get_object_or_404(Account, email=request.user)

        serializer = serializers.AccountSerializer(user, data=request.data)

        if serializer.is_valid():
            serializer.save()
            data = serializer.data
            data['email_verified'] = user.email_verified
            if user.plan != None:
                data['plan'] = user.plan.space_size
                data['plan_desc'] = user.plan.desc
                data['amount'] = user.plan.amount
            else:
                data['plan'] = None
                data['plan_desc'] = None
                data['amount'] = None
            data['profile_image'] = data['profile_image']
            data['success'] = "Success"

        else:
            data = serializer.errors   
        return Response(data,  status=status.HTTP_200_OK)



#Register users
class register_view(APIView):
    statusCode = None
    data = {}

    #The post request
    def post(self, request):
        data = {}                                                           #This is all the data that is been passed to the api Eg. Contex variables
        statusCode = ''                                                     #This is the status code for the request
        # current_site = get_current_site(request)
        serializer = serializers.RegisterSerializer(data=request.data)
        if serializer.is_valid():
            account = serializer.save()
            data['success'] = "Successfully registered."
            data['fullname'] = account.fullname
            data['username'] = account.username
            data['email'] = account.email
            statusCode = status.HTTP_200_OK 
        else:
            data = serializer.errors

        return Response(data)






#Login view for validation
class login_view(APIView):
    data = {}
    
    def post(self, request):
        credentials = request.data['username']
        password = request.data['password']
        # print(credentials)

        # Check if username or email exist 
        if Account.objects.filter(email=credentials).exists()==True:
            account_cred =  Account.objects.get(email=credentials) 	

        elif Account.objects.filter(username=credentials).exists()==True:
            account_cred =  Account.objects.get(username=credentials) 	

        else:
            account_cred = None
            self.data['error'] = "Username/Email not found"


        # If it does, it means the password doesnt match 
        if account_cred:
            # Check if username and passowrd match
            userAuth = authenticate(username=account_cred, password=password) 

            if userAuth is not None:					 		
                self.data['error'] = False
            else:
                self.data['error'] = "Incorrect password"



        return Response(self.data)


# Login with google 
@login_required(login_url=settings.DOMAIN_FRONTEND+"/home")
def googleLogin_view(request):

    context = {}
    newuser = "false"

    form = SocialLogin()
    form.user = request.user
    form.save()

    account =  Account.objects.get(email=request.user) 	

    if not account.email_verified:
        if account.first_name == None or account.last_name == None:
            splited_email = account.email.split('@')
            account.fullname = splited_email[0]
        else:
            account.fullname = account.first_name+" "+account.last_name
        account.registration = "google"
        account.save()
        newuser = "true"


    auth =  SocialLogin.objects.filter(user=request.user).order_by('-id').first()
    account.email_verified = True
    account.save()

    username = str(auth.user.username)
    token = str(auth.token)
    logout(request)

    return redirect(settings.DOMAIN_FRONTEND+"/accounts/login/"+username+"/"+token+"?newuser="+newuser)



#Email verification

#The browsable API link (Only for logged in users)
@api_view(['POST'])
@permission_classes([IsAuthenticated])
def verify_email_view(request):
    data = {}
    if request.user.email_verified is not True:
        current_site = get_current_site(request)
        send_email_verification(request, request.user, mail_subject="Verify your "+current_site.domain+" account.")
        data['success'] = "Verification email has been sent to " + request.user.email
    else:
        data['success'] = "Your email has been verified already"
        data['verified'] = True

    return Response(data)




@api_view(['POST'])
def welcome_email_view(request):
    data = {}
    account =  get_object_or_404(Account, email=request.data['email'])
    if account.email_verified is not True:
        send_email_verification(request, account, mail_subject="Welcome to Family Album ")
    else:
        data['verified'] = True
    data['success'] = "Success"
    return Response(data)


   
   


#The send email function
def send_email_verification(request, account, mail_subject):

    current_site = settings.DOMAIN_FRONTEND
    mail_subject = mail_subject
    to_email = account.email
    html_template = 'email.html'

    html_message = render_to_string(html_template, {
    'user':account, 'domain':current_site,
    'uid': urlsafe_base64_encode(force_bytes(account.pk)),
    'token': account_activation_token.make_token(account),
    })
    celery_verify_email.apply_async(args=(mail_subject, html_message,to_email))




#The email verification view
@api_view(['GET'])
def activate(request, uidb64, token):
    data = {}
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except:
        user = None
        data['error'] = "Activation link is invalid!"
        return Response(data)

    if user.email_verified:
        data['success'] = "Your email has been verified already."
        data['verified'] = True
    else:
        if user is not None and account_activation_token.check_token(user, token):
            user.email_verified = True
            user.save()
            # login(request, user)
            data['success'] = "Thank you for verifying your email. Now you can login your account."
        else:
            data['error'] = "Activation link is invalid!"

    return Response(data)
@api_view(['POST'])
def setting_password(request):
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']

    if password == confirm_password:
        user = request.user
        user.set_password(password)
        user.save()
        data ={}
        data['success'] = "Successfully set password"
        return Response(data=data)
    else:
        data ={}
        data['error'] = "Passwords do not match"
        return Response(data=data)

class WaitLists(APIView):
    data = {}
    
    def post(self, request):
        try:
            email = request.POST['email']
            WaitList.objects.create(email=email,joined =False)
            data ={}
            data['result'] = "Successfully joined waitlist"
            return Response(data=data)
        except:
            data ={}
            data['result'] = "email exist"
            return Response(data=data)


accounts/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.fullname }},

You're receiving this email because you have not verified the email address you use for Cloudiby.

Please <b>click</b> on the link below to verify your email:

http://{{ domain }}{% url 'accounts_api:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/email.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta charset="utf-8"> <!-- utf-8 works for most cases -->
    <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldn't be necessary -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
    <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">

    <!-- CSS Reset : BEGIN -->
    <style>

        /* What it does: Remove spaces around the email design added by some email clients. */
        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
        html,
body {
    margin: 0 auto !important;
    padding: 0 !important;
    height: 100% !important;
    width: 100% !important;
    background: #f1f1f1;
}

/* What it does: Stops email clients resizing small text. */
* {
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}

/* What it does: Centers email on Android 4.4 */
div[style*="margin: 16px 0"] {
    margin: 0 !important;
}

/* What it does: Stops Outlook from adding extra spacing to tables. */
table,
td {
    mso-table-lspace: 0pt !important;
    mso-table-rspace: 0pt !important;
}

/* What it does: Fixes webkit padding issue. */
table {
    border-spacing: 0 !important;
    border-collapse: collapse !important;
    table-layout: fixed !important;
    margin: 0 auto !important;
}

/* What it does: Uses a better rendering method when resizing images in IE. */
img {
    -ms-interpolation-mode:bicubic;
}

/* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */
a {
    text-decoration: none;
}

/* What it does: A work-around for email clients meddling in triggered links. */
*[x-apple-data-detectors],  /* iOS */
.unstyle-auto-detected-links *,
.aBn {
    border-bottom: 0 !important;
    cursor: default !important;
    color: inherit !important;
    text-decoration: none !important;
    font-size: inherit !important;
    font-family: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
}

/* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */
.a6S {
    display: none !important;
    opacity: 0.01 !important;
}

/* What it does: Prevents Gmail from changing the text color in conversation threads. */
.im {
    color: inherit !important;
}

/* If the above doesn't work, add a .g-img class to any image in question. */
img.g-img + div {
    display: none !important;
}

/* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */
/* Create one of these media queries for each additional viewport size you'd like to fix */

/* iPhone 4, 4S, 5, 5S, 5C, and 5SE */
@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
    u ~ div .email-container {
        min-width: 320px !important;
    }
}
/* iPhone 6, 6S, 7, 8, and X */
@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
    u ~ div .email-container {
        min-width: 375px !important;
    }
}
/* iPhone 6+, 7+, and 8+ */
@media only screen and (min-device-width: 414px) {
    u ~ div .email-container {
        min-width: 414px !important;
    }
}

    </style>

    <!-- CSS Reset : END -->

    <!-- Progressive Enhancements : BEGIN -->
    <style>

	    .primary{
	background: #2196F3;
}
.bg_white{
	background: #ffffff;
}
.bg_light{
	background: #fafafa;
}
.bg_black{
	background: #000000;
}
.bg_dark{
	background: rgba(0,0,0,.8);
}
.email-section{
	padding:2.5em;
}

/*BUTTON*/
.btn{
	padding: 10px 15px;
	display: inline-block;
    border: 0px;
}
.btn.btn-primary{
	border-radius: 5px;
	background: #2196F3;
	color: #ffffff;
}
.btn.btn-white{
	border-radius: 5px;
	background: #ffffff;
	color: #000000;
}
.btn.btn-white-outline{
	border-radius: 5px;
	background: transparent;
	border: 1px solid #fff;
	color: #fff;
}
.btn.btn-black-outline{
	border-radius: 0px;
	background: transparent;
	border: 2px solid #000;
	color: #000;
	font-weight: 700;
}

h1,h2,h3,h4,h5,h6{
	font-family: 'Lato', sans-serif;
	color: #000000;
	margin-top: 0;
	font-weight: 400;
}

body{
	font-family: 'Lato', sans-serif;
	font-weight: 400;
	font-size: 15px;
	line-height: 1.8;
	color: rgba(0,0,0,.4);
}

a{
	color: #2196F3;
}

table{
}
/*LOGO*/

.logo h1{
	margin: 0;
}
.logo h1 a{
	color: #2196F3;
	font-size: 24px;
	font-weight: 700;
	font-family: 'Lato', sans-serif;
}

/*HERO*/
.hero{
	position: relative;
	z-index: 0;
}

.hero .text{
	color: rgba(0,0,0,.3);
}
.hero .text h2{
	color: #000;
	font-size: 40px;
	margin-bottom: 0;
	font-weight: 400;
	line-height: 1.4;
}
.hero .text h3{
	font-size: 24px;
	font-weight: 300;
}
.hero .text h2 span{
	font-weight: 600;
	color: #2196F3;
}


/*HEADING SECTION*/
.heading-section{
    
}
.heading-section h2{
	color: #000000;
	font-size: 28px;
	margin-top: 0;
	line-height: 1.4;
	font-weight: 400;
}
.heading-section .subheading{
	margin-bottom: 20px !important;
	display: inline-block;
	font-size: 13px;
	text-transform: uppercase;
	letter-spacing: 2px;
	color: rgba(0,0,0,.4);
	position: relative;
}
.heading-section .subheading::after{
	position: absolute;
	left: 0;
	right: 0;
	bottom: -10px;
	content: '';
	width: 100%;
	height: 2px;
	background: #2196F3;
	margin: 0 auto;
}

.heading-section-white{
	color: rgba(255,255,255,.8);
}
.heading-section-white h2{
	font-family:none ;
	line-height: 1;
	padding-bottom: 0;
}
.heading-section-white h2{
	color: #ffffff;
}
.heading-section-white .subheading{
	margin-bottom: 0;
	display: inline-block;
	font-size: 13px;
	text-transform: uppercase;
	letter-spacing: 2px;
	color: rgba(255,255,255,.4);
}


ul.social{
	padding: 0;
}
ul.social li{
	display: inline-block;
	margin-right: 10px;
}

/*FOOTER*/

.footer{
	border-top: 1px solid rgba(0,0,0,.05);
	color: rgba(0,0,0,.5);
}
.footer .heading{
	color: #000;
	font-size: 20px;
}
.footer ul{
	margin: 0;
	padding: 0;
}
.footer ul li{
	list-style: none;
	margin-bottom: 10px;
}
.footer ul li a{
	color: rgba(0,0,0,1);
}


@media screen and (max-width: 500px) {


}


    </style>


</head>

<body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;">
	<center style="width: 100%; background-color: #f1f1f1;">
    <div style="max-width: 600px; margin: 0 auto;" class="email-container">
    	<!-- BEGIN BODY -->
      <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin: auto;">
      	<tr>
          <td valign="top" class="bg_white" style="padding: 1em 2.5em 0 2.5em;">
          	<table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
          		<tr>
          			<td class="logo" style="text-align: center;">
			            <h1>Verification</h1>
			          </td>
          		</tr>
          	</table>
          </td>
	      </tr><!-- end tr -->
	      <tr>
          <td valign="middle" class="hero bg_white" style="padding: 3em 0 2em 0;">
            <!-- <img src="https://cloudiby-test.netlify.app/logo.png" alt="" style="width: 300px; max-width: 600px; height: auto; margin: auto; display: block;"> -->
            <img src="https://cloudiby-test.netlify.app/logo.png" alt="" style="width: 100px; max-width: 100px; height: auto; margin: auto; display: block;">
          </td>
	      </tr><!-- end tr -->
				<tr>
          <td valign="middle" class="hero bg_white" style="padding: 2em 0 4em 0;">
            <table>
            	<tr>
            		<td>
            			<div class="text" style="padding: 0 2.5em; text-align: center;">
                            <h3><b>Hi {{ user.fullname }},</b></h3>
            				<h3>Please on the link below to verify your email</h3>
                            <p>You're receiving this email because you have not verified the email address you use for Cloudiby.</p>
            				<p><b><a href="{{ domain }}{% url 'accounts_api:activate' uidb64=uid token=token %}"><span style="font-size: 22px;">Verify my account</span></a></b></p>
            			</div>
            		</td>
            	</tr>
            </table>
          </td>
	      </tr><!-- end tr -->
      <!-- 1 Column Text + Button : END -->
      </table>
      <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin: auto;">
      	
        <tr>
          <td class="bg_light" style="text-align: center;">
          	<p> <center>Cloudiby.  </center></p>
          </td>
        </tr>
      </table>

    </div>
  </center>
</body>
</html>